1 -- Create the polls table                                                         │
 │     2 CREATE TABLE polls (                                                              │
 │     3   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),                                  │
 │     4   user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,                       │
 │     5   question TEXT NOT NULL,                                                         │
 │     6   options TEXT[] NOT NULL,                                                        │
 │     7   created_at TIMESTAMPTZ DEFAULT now()                                            │
 │     8 );                                                                                │
 │     9                                                                                   │
 │    10 -- Create the votes table                                                         │
 │    11 CREATE TABLE votes (                                                              │
 │    12   id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,                         │
 │    13   poll_id UUID REFERENCES polls(id) ON DELETE CASCADE,                            │
 │    14   user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,                       │
 │    15   option_index INTEGER NOT NULL,                                                  │
 │    16   created_at TIMESTAMPTZ DEFAULT now(),                                           │
 │    17   -- Add a unique constraint to ensure one vote per user per poll                 │
 │    18   CONSTRAINT votes_poll_id_user_id_key UNIQUE (poll_id, user_id)                  │
 │    19 );                                                                                │
 │    20                                                                                   │
 │    21 -- Create a profiles table to store public user data                              │
 │    22 CREATE TABLE profiles (                                                           │
 │    23   id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,                │
 │    24   username TEXT UNIQUE,                                                           │
 │    25   full_name TEXT,                                                                 │
 │    26   avatar_url TEXT,                                                                │
 │    27   updated_at TIMESTAMPTZ                                                          │
 │    28 );                                                                                │
 │    29                                                                                   │
 │    30 -- Set up Row Level Security (RLS)                                                │
 │    31 ALTER TABLE polls ENABLE ROW LEVEL SECURITY;                                      │
 │    32 ALTER TABLE votes ENABLE ROW LEVEL SECURITY;                                      │
 │    33 ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;                                   │
 │    34                                                                                   │
 │    35 -- Create policies for polls                                                      │
 │    36 CREATE POLICY "Allow logged-in users to create polls" ON polls FOR                │
 │       INSERT WITH CHECK (auth.role() = 'authenticated');                                │
 │    37 CREATE POLICY "Allow users to view all polls" ON polls FOR SELECT                 │
 │       USING (true);                                                                     │
 │    38 CREATE POLICY "Allow owners to update their own polls" ON polls FOR               │
 │       UPDATE USING (auth.uid() = user_id);                                              │
 │    39 CREATE POLICY "Allow owners to delete their own polls" ON polls FOR               │
 │       DELETE USING (auth.uid() = user_id);                                              │
 │    40                                                                                   │
 │    41 -- Create policies for votes                                                      │
 │    42 CREATE POLICY "Allow logged-in users to vote" ON votes FOR INSERT WITH            │
 │       CHECK (auth.role() = 'authenticated');                                            │
 │    43 CREATE POLICY "Allow users to view all votes" ON votes FOR SELECT                 │
 │       USING (true);                                                                     │
 │    44 CREATE POLICY "Allow users to update their own vote" ON votes FOR                 │
 │       UPDATE USING (auth.uid() = user_id);                                              │
 │    45                                                                                   │
 │    46 -- Create policies for profiles                                                   │
 │    47 CREATE POLICY "Allow users to view all profiles" ON profiles FOR                  │
 │       SELECT USING (true);                                                              │
 │    48 CREATE POLICY "Allow users to insert their own profile" ON profiles               │
 │       FOR INSERT WITH CHECK (auth.uid() = id);                                          │
 │    49 CREATE POLICY "Allow users to update their own profile" ON profiles               │
 │       FOR UPDATE USING (auth.uid() = id);            
